### ISSUE TITLE
error about StarCraftII

### ISSUE THREAD

**Issue by jh12521** [lilh76/MACPro#1]
Hello, your work is great. When I run the following command, 
python src/main.py --config=qmix_macpro_rnn/qmix_macpro_attn --task-config=marines/sz
there is an error,
FileNotFoundError: [Errno 2] No such file or directory: '/home/jh/Downloads/software/academic-project/continual_learning/MACPro-main/3rdparty/StarCraftII/Versions'
How can I solve it? I would greatly appreciate it if I could receive your reply

**Comment by LLLLLH76** [comment]
The error you encountered indicates that the StarCraft II game files are missing or not set up correctly in the expected directory. To resolve this, please follow the installation instructions provided in the script [install_sc2.sh](https://github.com/oxwhirl/pymarl/blob/master/install_sc2.sh). This script will guide you through downloading and setting up the StarCraft II environment.

After completing the installation, ensure that the game files are placed in the correct path as expected by the project (e.g., `/home/jh/Downloads/software/academic-project/continual_learning/MACPro-main/3rdparty/StarCraftII/`).

**Comment by lilh76** [comment]
The error you encountered indicates that the StarCraft II game files are missing or not set up correctly in the expected directory. To resolve this, please follow the installation instructions provided in the script [install_sc2.sh](https://github.com/oxwhirl/pymarl/blob/master/install_sc2.sh). This script will guide you through downloading and setting up the StarCraft II environment.

After completing the installation, ensure that the game files are placed in the correct path as expected by the project (e.g., /home/jh/Downloads/software/academic-project/continual_learning/MACPro-main/3rdparty/StarCraftII/).
