### ISSUE TITLE
StarCraftII maps

### ISSUE THREAD

**Issue by jh12521** [lilh76/MACPro#2]
Hello, your work is great, but I found that your code does not provide the maps' 13m 'and' 4m 'in marines, as well as the maps' 2s1z-vs_3z' and '2s2z-vs_4s' in SZ. Where can I get these maps?

**Comment by LLLLLH76** [comment]
Hello, thank you for your feedback and for appreciating our work!

The maps you mentioned (`13m`, `4m`, `2s1z-vs_3z`, and `2s2z-vs_4s`) are indeed included in the repository. You can find them in the following directory:  
`src/envs/smac/smac/env/starcraft2/maps/SMAC_Maps`.

Please ensure that you have cloned the repository properly and that this directory exists in your local setup. If the issue persists, feel free to share more details about your setup or the specific problem you’re encountering, and I’d be happy to help further!

**Comment by lilh76** [comment]
Hello, thank you for your feedback and for appreciating our work!

The maps you mentioned (13m, 4m, 2s1z_vs_3z, and 2s2z_vs_4s) are indeed included in the repository. You can find them in the following directory:
src/envs/smac/smac/env/starcraft2/maps/SMAC_Maps.

Please ensure that you have cloned the repository properly and that this directory exists in your local setup. If the issue persists, feel free to share more details about your setup or the specific problem you’re encountering, and I’d be happy to help further!
